
name: "actions-setup-redis"
description: "setup redis database"
author: "Ichinose Shogo"
on : pushsteps:
- uses: actions/checkout@v3
- uses: shogo82148/actions-setup-redis@v1
  with:
    redis-version: '6.x'
- run: redis-cli ping
